# -*- coding: utf-8 -*-
"""GeradorSenhas_.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sYm9javGo6byqccArKOLn6cde0a_ABzG

<h1>Gerador de Senha Segura 🔐</h1><hr>

<p>
    Esse programa se baseia em uma atividade realizada diariamente por todos os usuários da internet mundial.<br>
    O uso de <strong>senha segura</strong> tem sido muito lembrado quando o tema <em>Cibersegurança</em> está sendo abordado.<br>
    Através do artigo <a href="https://www.kaspersky.com.br/resource-center/threats/how-to-create-a-strong-password" target="_blank">Senhas fortes: como criá-las e quais seus benefícios</a> publicado no site da empresa russa Kaspersky,<br>decidi usar algumas das dicas para criar o meu gerador de senhas.<br><br><br>
</p>

<h2>Programa - Gerador de Senhas 💻</h2>
<hr>
"""

from random import choice ### Importar a biblioteca random para usar a função choice
import string ### Importa a biblioteca String para usar funções de caracteres

caracteres_disponiveis = string.ascii_letters + string.digits + string.punctuation ### Une todos os caracteres possíveis
senha_gerada = ('') ### String vazia para receber lá na frente a senha gerada

for character in range (1, 13):  ### Percorre os caracteres disponiveis por 12 vezes
    senha_gerada += choice(caracteres_disponiveis) ### A cada vez que percorrer, adiciona um dos caracteres a variável senha

arquivo = open('password.txt', 'a') ### cria e abre o arquivo password.txt; parametro 'a' para modo de uso 'Escrita. Insere novos dados no fim do arquivo'
arquivo.write(senha_gerada + '\n') ### write recebe a senha gerada e o escreve no arquivo
arquivo.close() ### fecha o arquivo e salva após utilizar o mesmo

print(f'\nSenha gerada com sucesso\n{senha_gerada}') ### Mostra a senha gerada

"""<br><br><h2>Verificações de Segurança 🔎</h2><hr>

<ol>
    <li type='none'><strong>1) Ela é longa? Tente usar pelo menos 10 ou 12 caracteres, ou o máximo possível.</strong></li>
</ol>

<p>
    Nossas senhas possuem 12 caracteres e nos oferece opção para aumentar a quantidade se necessário.<br>
    Vamos ver abaixo algumas das nossas senhas geradas:<br>

    bz?IJ"E\MTt?
    #f90cr6LwU8D
    
Então, <strong>sim</strong>. A nossa senha é longa, possui 12 caracteres fixos, mas pode ser feita variação.
</p><br>

<ol>
    <li type='none'><strong>2) Ela é difícil de adivinhar?</strong></li>
</ol>

<p>
    Sim. Usamos caracteres diversos e variados entre si para dificultar a memorização e evitar palavras comuns.
</p><br>

<ol>
    <li type='none'><strong>3) Ele tem tipos variados de caracteres?</strong></li>
</ol>
<p>
    Sim. Usamos letras, números, pontuações e símbolos. Assim, tornamos a senha mais imprevisível.
</p><br>

<ol>
    <li type='none'><strong>4) Substituições óbvias de caracteres são evitadas? Por exemplo, usar o número zero "0" no lugar da letra "O".</strong></li>
</ol>
<p>
    Esse algoritmo faz essa alteração, não como um humano faria entendendo que ele está usando um caractere substituindo outro.<br>
    Por agir de forma extremamente literal, nosso algoritmo substitui caracteres de forma lógica e não racional. Ainda assim, é eficiente.
</p><br>

<ol>
    <li type='none'><strong>5) A senha usa combinações de palavras incomuns?</strong></li>
</ol>
<p>
    O algoritmo faz o uso do código <strong>ASCII</strong> (<em>American Standard Code for Information Interchange ou ”Código Padrão Americano para o Intercâmbio de Informação”</em>). Usando a <strong>biblioteca string</strong> do <em>Python</em> importamos letras, números, pontuações e símbolos como já citado anteriormente.<br>
    Essa utilização de forma automatizada dos caracteres, em geral, torna a nossa senha especial sendo ela incomum e improvável.
</p><br>

<ol>
    <li type='none'><strong>6) Você consegue memorizá-la?</strong></li>
</ol>
<p>
    A princípio, temos dificuldade em memorizar as senhas geradas automaticamente. Ainda assim, senhas <em>semilegíveis</em> podem facilitar a memorização com o tempo. Por esse motivo, usamos aleatoriamente todos os caracteres durante a geração de senha.<br>
    Se mantivermos senhas que dificultem a memorização e que não sejam semilegíveis, teremos maior chances de ter uma senha segura. É interessante também manter um gerenciador de senhas, assim, podendo evitar a troca constante de senha por esquecimento.
</p><br>

<ol>
    <li type='none'><strong>7) Você já usou a senha antes?</strong></li>
</ol>
<p>
    Através do gerador de senhas, as chances de usar uma senha repetida é praticamente impossível. Devido a sua grande quantidade de caracteres disponíveis e a suas vastas possibilidades de combinações, podemos gerar com segurança senhas únicas.
</p><br>

<ol>
    <li type='none'><strong> 8) A senha apresenta uma regra difícil de ser adivinhada por computadores?</strong></li>
</ol>
<p>
    <strong>Sim</strong>. Um computador poderia até trabalhar duro para tentar adivinhar a senha, mas, ele não adivinharia após termos seguido todas as etapas anteriores para poder gerar senhas fortemente seguras, podendo dar tranquilidade aos utilizadores.
</p><br>

<h2>Considerações Finais 📑</h2><hr>

<p>
    Essa atividade pessoal, junto as dicas oferecidas no artigo, me proporcionaram um bom estudo e analise do que foi construído. Procurando encontrar possíveis fraquezas, volatilidade durante o uso constante do gerador de senhas e, se de alguma forma, ele poderia ser útil e eficaz no que foi proposto a fazer. Apesar de sua simplicidade, acredito ter sido um programa que traz sucesso a solução do que foi proposto:<strong> gerar senhas seguras para qualquer tipo de usuário</strong>.<br>
    Acrescentei por questões de aprendizado, um arquivo que salva de forma automática cada senha gerada após executar o programa. Claro, não é seguro, mas, com ajustes e criptografia, poderíamos manter neste programa um gerador e gerenciador de senhas.<br>
    Em todo caso, a segurança deve ser bem explorada, devem ser feitas analises robustas para uma possível aplicação da solução.
</p><br>
<em>Roger Rodrigo Alves - Estudante de Python 🐍, Análise de Dados📈, e Ciência de Dados 📊</em>
"""